[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jitter_correction"
version = "0.2.0"
authors = [
    {name = "Ross Jennings", email = "ross.jennings@nanograv.org"},
]
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "numba",
    "toml",
    "pywavelets",
    "h5py",
    "loguru",
]

[project.scripts]
jc-datagen = "jitter_correction.scripts.datagen:main"
jc-extract-pcs = "jitter_correction.scripts.extract_pcs:main"
jc-template-stats = "jitter_correction.scripts.template_stats:main"
jc-pca-timing = "jitter_correction.scripts.pca_timing:main"
jc-pca-score-timing = "jitter_correction.scripts.pca_score_timing:main"
