[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jitter_correction"
version = "0.2.0"
authors = [
    {name = "Ross Jennings", email = "ross.jennings@nanograv.org"},
]
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.21.3",
    "scipy>=1.7.2",
    "matplotlib>=3.5.0",
    "numba>=0.57.0",
    "toml>=0.10.2",
    "pywavelets>=1.2.0",
    "h5py>=3.6.0",
    "loguru>=0.7.3",
]

[project.scripts]
jc-datagen = "jitter_correction.scripts.datagen:main"
jc-extract-pcs = "jitter_correction.scripts.extract_pcs:main"
jc-template-stats = "jitter_correction.scripts.template_stats:main"
jc-pca-timing = "jitter_correction.scripts.pca_timing:main"
jc-pca-score-timing = "jitter_correction.scripts.pca_score_timing:main"

[tool.setuptools.package-data]
jitter_correction = ["py.typed"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
numpy = ">=1.21.3"
scipy = ">=1.7.2"
matplotlib = ">=3.5.0"
numba = ">=0.57.0"
toml = ">=0.10.2"
pywavelets = ">=1.2.0"
h5py = ">=3.6.0"
loguru = ">=0.7.3"

[tool.pixi.pypi-dependencies]
jitter-correction = {path = ".", editable = true}

[tool.pixi.tasks]
mypy = {cmd = "mypy jitter_correction"}
type-check = {depends-on = [{task = "mypy", environment = "mypy"}]}

[tool.pixi.environments]
default = {features = ["ipykernel"]}
mypy = {features = ["mypy"]}

[tool.pixi.feature.ipykernel.dependencies]
ipython = "*"
ipykernel = ">=6.22.0,<7" # v7 leads to weird plot issues with numba
ipympl = "*"

[tool.pixi.feature.ipykernel.tasks]
install-kernel = "python -m ipykernel install --user --name jitter-correction"

[tool.pixi.feature.mypy.dependencies]
mypy = "*"
scipy-stubs = "*"
types-toml = "*"

[tool.mypy]
allow_redefinition = true

[[tool.mypy.overrides]]
module = ["numba.*"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["pywt.*"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["h5py.*"]
ignore_missing_imports = true
