import numpy as np
from collections.abc import Callable

from .toas import TemplateMatchingEstimator
from .signal import fft_roll
from .profile_data import ProfileData

def get_template(
    data: ProfileData,
    n_iter: int | np.integer = 1,
) -> np.ndarray:
    '''
    Create a template by iteratively aligning and averaging profiles.
    Starts by averaging the middle 10% of profiles and iterates `n_iter` times,
    each time aligning the pulses using the previous template and averaging
    to create a new template.
    '''
    n = data.n_profiles
    n_5_percent = n//20
    sl = slice(n//2 - n_5_percent, n//2 + n_5_percent)
    template = np.mean(data.profiles[sl], axis=0)
    toas = np.empty(data.n_profiles)

    for i in range(n_iter):
        estimator = TemplateMatchingEstimator(template)
        toas[:] = estimator.estimate_toas(data).toa
        profiles_aligned = np.empty_like(data.profiles)
        for j, profile in enumerate(data.profiles):
            profiles_aligned[j] = fft_roll(profile, -toas[j])

        template = np.mean(profiles_aligned, axis=0)

    return template

def calc_dtoas(
    template: np.ndarray,
    data: ProfileData,
    poly_degree: int | np.integer = 1,
) -> np.ndarray:
    '''
    Calculate ΔTOAs from profiles with polynomial drift.
    '''
    profile_number = np.arange(data.n_profiles)
    estimator = TemplateMatchingEstimator(template)
    toas = estimator.estimate_toas(data)
    timing_poly_coeffs = np.polyfit(profile_number, toas, poly_degree) # type: ignore
    timing_poly_vals = np.polyval(timing_poly_coeffs, profile_number)
    dtoas = toas - timing_poly_vals

    return dtoas

def test_toa_recovery(
    func: Callable,
    template: np.ndarray,
    n: int | np.integer,
    rms_toa: float | np.floating,
    snr: float | np.floating = np.inf,
    dt: float | np.floating = 1.,
    tol: float | np.floating = np.sqrt(np.finfo(np.float64).eps),
) -> tuple[np.floating, np.floating]:
    '''
    Test function for `toa_ws()` and `toa_fourier()`.
    Attempts to recover `n` TOAs at a given SNR and returns the RMS error.

    `func`:     Function to test (`toa_ws` or `toa_fourier`).
    `template`: Template to use. Test profiles will be generated by
                shifting it.
    `n`:        Number of test profiles to generate.
    `rms_toa`:  RMS TOA for test profiles.
    `snr`:      Signal-to-noise ratio of the test profiles
    `dt`:       The width of each phase bin in the profile.
                Sets the units of the TOA.
    `tol`:      Relative tolerance for optimization.
    '''
    dtoas: Any = []
    toa_errs: Any = []
    for i in range(n):
        true_toa = rms_toa*randn()
        profile = fft_roll(template, true_toa/dt)
        if np.isfinite(snr):
            profile += randn(len(profile))/snr
        result = func(template, profile, dt=dt, tol=tol)
        toa_estimate = result.toa
        dtoas.append(toa_estimate-true_toa)
        toa_errs.append(result.error)
    dtoas = np.array(dtoas)
    toa_errs = np.array(toa_errs)
    return np.sqrt(np.mean(dtoas**2)), np.sqrt(np.mean(toa_errs**2))
