[data]
  n_profiles = 512
  npprof = 1000
  n_bins = 1024
  snr = 1000
  drift_bins = 50

[pulse_spec]
  amplitude = [0.8, 1.0, 0.4]
  loc = [-0.08, 0.00, 0.06]
  fwhm = [0.04, 0.06, 0.05]
  fj = [0.0, 0.0, 0.0]
  modindex = [1.0, 1.0, 1.0]
